baseURL: "https://arabic.page"
languageCode: "en-us"
title: "Arabic.Page"

taxonomies:
  category: "categories"
  dialect: "dialects"
  subject: "subjects"
  instructor: "instructors"
  language: "languages"
  tag: "tags"

outputs:
  home:
    - HTML
    - RSS

params:
  author:
    name: Linguist | اللُّــغَــوِيّــــ
    github: https://github.com/linguistpage
    email: linguist.page@gmail.com
    channel: https://t.me/thearabicpage
    donate: https://awtad.ngo/donate

copyright: © 2024 Linguist | اللُّــغَــوِيّــــ.
