baseURL: "https://arabic.page"
languageCode: "en-us"
title: "Arabic.Page"

taxonomies:
  category: "categories"
  dialect: "dialects"
  subject: "subjects"
  instructor: "instructors"
  language: "languages"
  tag: "tags"

outputs:
  home:
    - HTML
    - RSS
